// lib/copy.js
export const copy = {
  checkoutUrl: "https://www.oriopay.app/p/naturali-kosmetika",

  metadata: {
    title: "Natūralios kosmetikos vadovas",
    description:
      "80 receptų 100 % natūraliai kosmetikai, kurią galite pasigaminti namuose. Išbandytos ir saugios formulės odos priežiūrai ir vengiant toksiškų chemikalų.",
  },

  hero: {
    headlineLine1: "80 receptų",
    headlineHighlight: "NATŪRALIAI KOSMETIKAI",
    subheadline:
      "Gaukite prieigą prie slaptų 100 % natūralios kosmetikos receptų ir kurkite ją patogiai savo namuose! Išbandytos ir saugios formulės, kad apsaugotumėte savo šeimą ir atsisakytumėte pramoninių gaminių, pilnų toksinų.",
    cta: "NORIU PRIEIGOS DABAR!",
    imageAlt: "Natūralios kosmetikos vadovas",
    timerLabels: {
      days: "Dienos",
      hours: "Valandos",
      minutes: "Minutės",
      seconds: "Sekundės",
    },
  },

  story: {
    text: "Dabar pateiksiu jums praktišką vadovą – tiesiai prie esmės, be jokių bereikalingų komplikacijų, bet itin patikimą, kad galėtumėte kurti savo 100 % natūralią kosmetiką namuose. Neišleisdami krūvos pinigų, nepriklausydami nuo tūkstančių ingredientų – su džiaugsmu naudoti ją sau, dovanoti artimiesiems ir visiems kartu mėgautis 100 % saugia bei sveika priežiūra!",
    imageAlt: "Natūrali kosmetika",
  },

  recipeList: {
    headline: "Atraskite",
    headlineHighlight: "80 receptų,",
    headlineSuffix: "kuriuos gausite „Natūralios kosmetikos vadove“:",
    cta: "NORIU JŲ!",
    col1: [
      "Raminamasis kūno kremas",
      "Kūno kremas su pantenoliu",
      "Gaivinamasis kūno losjonas",
      "Kūno kremas-suflė",
      "Kūno sviestas su urukumu (anatu)",
      "Kietasis kūno sviestas",
      "Kūno aliejus",
      "Terapinis aliejus nuo dėmių ir strijų",
      "Dvofazis kūno aliejus",
      "Natūralus įdegio losjonas",
      "Skystas kūno muilas",
      "Dušo želė",
      "Kietasis kūno muilas su SCI",
      "Tradicinis kietasis kūno muilas",
      "Kreminis drėkinamasis muilas",
      "Šveičiamasis kūno muilas (Soap Body Scrub)",
      "Kūno šveitiklis",
      "Kūno šveitiklis su migdolų miltais",
      "Natūrali kūno priemonė su švytėjimo efektu",
      "Kūno purškiklis (Body Splash)",
      "Veido kremas su vitaminu C",
      "Veido kremas po saulės su levandomis",
      "Veido kremas su moliu",
      "Drėkinamasis veido losjonas su jazminais",
      "Sausasis veido aliejus (Dry Oil)",
      "Skystas veido muilas",
      "Veido prausimosi putos",
      "Veido serumas sausai ir jautriai odai",
      "Veido serumas riebiai odai",
      "Paakių serumas",
      "Veido tonikas sausai ir jautriai odai",
      "Gaivinamasis veido tonikas riebiai odai",
      "Veido valymo aliejus (Cleansing Oil)",
      "Veido valymo balzamas (Cleansing Balm)",
      "Muilas su raudonuoju moliu – Detoksikacija ir atgaivinimas",
      "Švelnus veido šveitiklis",
      "Veido gelis su salicilo rūgštimi",
      "Gelinė veido kaukė su hialurono rūgštimi",
      "Rožių veido eliksyras",
      "Veido purškiklis su alaviju",
      "Kaukė garbanotiems ir banguotiems plaukams",
    ],
    col2: [
      "Kaukė tiesiems ir šiek tiek banguotiems plaukams",
      "Kreminis kondicionierius",
      "Kietasis kondicionierius garbanotiems ir banguotiems plaukams",
      "Kietasis kondicionierius šiek tiek banguotiems ir tiesiems plaukams",
      "Kietasis šampūnas garbanotiems ir banguotiems plaukams",
      "Kietasis šampūnas tiesiems ir šiek tiek banguotiems plaukams",
      "Skystas šampūnas",
      "Kreminis šampūnas „2 viename“",
      "Vaikiškas šampūnas",
      "Nenuplaunamas kondicionierius (Leave-In)",
      "Nuo karščio apsaugantis plaukų purškiklis",
      "Plaukų aliejus",
      "Plaukų želė",
      "Natūrali plaukų pomada",
      "Drėkinamasis baigiamasis purškiklis",
      "Galvos odos šveitiklis",
      "Plaukų augimą skatinantis tonikas",
      "Serumas skilinėjantiems galiukams",
      "Plaukų kvepalai",
      "Natūralus intymios higienos muilas",
      "Natūralus vaikiškas kūno muilas",
      "Natūralūs skystieji kvepalai",
      "Natūralūs kietieji kvepalai",
      "Gelinė dantų pasta",
      "Burnos skalavimo skystis",
      "Purškiamasis dezodorantas",
      "Tepalas su medetkomis",
      "Tepalas su arnika",
      "Maitinamasis lūpų balzamas",
      "Natūralūs lūpų dažai",
      "Natūralus lūpų šveitiklis",
      "Purškiamasis makiažo valiklis",
      "Skutimosi putos",
      "Natūralus losjonas po skutimosi",
      "Rankų ir pėdų kremas",
      "Fiksuojamasis antakių gelis",
      "Natūrali masažinė žvakė",
      "Maitinamasis nagų ir odelių serumas",
      "Natūralus repelenton",
      "Atgaivinančios vonios druskos",
    ],
  },

  whatYouGet: {
    headline: "KĄ RASITE ŠIAME IŠSKIRTINIAME VADOVE?",
    cta: "GAUTI VADOVĄ DABAR!",
    imageAlt: "Ką rasite vadove",
    items: [
      "Daugiau nei 80 išbandytų ir patikrintų receptų – įskaitant kreminį šveičiamąjį muilą, sausąjį veido aliejų, kūno purškiklį, apsaugą plaukams nuo karščio ir daugybę naujų, inovatyvių formulių.",
      "Kremų, gelių, šampūnų ir muilų bazės – išmokite kurti 100 % saugius ir personalizuotus gaminius kiekvienam odos bei plaukų tipui.",
      "Išsamus žingsnis po žingsnio vadovas pradedantiesiems ir pažengusiems – perpraskite viską nuo pagrindinių koncepcijų iki sudėtingiausių kosmetikos gamybos technikų.",
      "Žaliavų katalogas – atraskite įvairių natūralių ingredientų naudą, kad sukurtumėte aukštos kokybės ir gryną kosmetiką.",
      "Kosmetologijoje taikoma fitoterapija – kaip panaudoti gydomuosius augalus, siekiant maksimaliai sustiprinti kosmetikos poveikį.",
      "Natūralaus formulavimo paslaptys – pH reguliavimas, natūralus konservavimas, žaliavų parinkimas ir efektyviausios sinergijos.",
      "Patarimai tobulai namų gamybai – paverskite savo virtuvę saugia vieta švarios kosmetikos kūrimui ir tobulinkite savo įgūdžius.",
      "Tvarumas ir rūpinimasis aplinka – išmokite kurti visiškai biologiškai skaidžią ir planetai draugišką kosmetiką.",
    ],
  },

  testimonials: {
    headline: "PAŽIŪRĖKITE, KĄ SAKO MOTERYS, KURIOS JAU NAUDOJASI ŠIUO VADOVU:",
    cta: "PRISIJUNGTI PRIE JŲ!",
    cards: [
      {
        name: "Marija S.",
        initials: "MS",
        color: "#16a34a",
        stars: 5,
        text: "Dievinu šį vadovą! Jau pasigaminau raminamąjį kūno kremą ir veido muilą – gavosi tiesiog nuostabiai. Daug geriau nei pramoniniai gaminiai, kuriuos naudojau anksčiau. Labai rekomenduoju visoms!",
        source: "WhatsApp",
      },
      {
        name: "Elena G.",
        initials: "EG",
        color: "#0f766e",
        stars: 5,
        text: "Mielosios, koks nuostabus vadovas! Receptai labai detalūs ir lengvai suprantami. Jau pagaminau kelis produktus draugėms dovanų ir jos juos tiesiog įsimylėjo. Vertas kiekvieno cento!",
        source: "WhatsApp",
      },
      {
        name: "Silvija R.",
        initials: "SR",
        color: "#7c3aed",
        stars: 5,
        text: "Šiek tiek dvejojau prieš pirkdama, bet tikrai buvo verta! Žaliavų katalogas labai padėjo suprasti ingredientus. Jau išbandžiau 6 skirtingus receptus ir visi pavyko nepriekaištingai.",
        source: "WhatsApp",
      },
      {
        name: "Daiva M.",
        initials: "DM",
        color: "#b45309",
        stars: 5,
        text: "Kokia neįtikėtina investicija! Naudodamasi vadovu pagaliau išmokau pasigaminti kietąjį šampūną ir kondicionierių. Mano plaukai atgijo, yra daug sveikesni, o kas mėnesį sutaupau krūvą pinigų kosmetikai. Ačiū!",
        source: "WhatsApp",
      },
    ],
  },

  autonomyIntro: {
    text1: "Su „Natūralios kosmetikos vadovu“ išmoksite kurti savo gaminius visiškai nuo nulio.",
    text2: "Jame žingsnis po žingsnio parodoma, kaip sąmoningai išsirinkti natūralius ingredientus, pritaikyti formules skirtingiems odos tipams ar plaukų poringumui ir personalizuoti produktus taip, kad jie idealiai atitiktų jūsų poreikius.",
    text3: "Įgausite pasitikėjimo ir visišką savarankiškumą formuluojant. Galėsite testuoti bei tobulinti receptus, kurdami unikalią kosmetiką su savitu charakteriu. Dėka itin detalaus natūralių žaliavų katalogo, pažinsite geriausius ingredientus ir atrasite idelius derinius kiekvienam gaminio tipui.",
    cta: "GAUTI VADOVĄ!",
    imageAlt: "Savarankiškumas gaminant natūralią kosmetiką",
  },

  benefitsList: {
    headline: "Nepriklausomybė ir kūrybiškumas natūralios priežiūros pasaulyje!",
    cta: "NORIU PRIEIGOS DABAR!",
    items: [
      {
        bold: "Išmokite kurti",
        rest: " kremus, serumus, šampūnus, muilus ir daug kitų priežiūros priemonių.",
      },
      {
        bold: "Atraskite, kaip neklystant išsirinkti",
        rest: " tinkamus ingredientus kiekvienam specifiniam odos ir plaukų poreikiui.",
      },
      {
        bold: "Išsilaisvinkite nuo pramoninės chemijos ir",
        rest: " kurkite 100 % personalizuotas, natūralias formules.",
      },
      {
        bold: "Pasinerkite į kosmetologijoje taikomą fitoterapiją,",
        rest: " semdamiesi gydomųjų augalų ir ekstraktų savybių.",
      },
      {
        bold: "Ženkliai sumažinkite išlaidas,",
        rest: " gamindami savo kosmetiką ir nedarydami jokių kompromisų jos kokybei.",
      },
      {
        bold: "Gaukite prieigą prie profesionalių receptų",
        rest: " ir išmokite saugiai kurti aukščiausios klasės produktus.",
      },
      {
        bold: "Suteikite savo odai geriausią priežiūrą,",
        rest: " tiksliai žinodami, kokius grynus ingredientus naudojate.",
      },
      {
        bold: "Apsaugokite savo šeimos sveikatą",
        rest: " naudodami gaminius be žalingų konservantų ir dirbtinių dažiklių.",
      },
    ],
  },

  economy: {
    headline: "Sutaupymas ir sveika priežiūra be jokio gramo chemijos!",
    text1: "Nuosavos natūralios kosmetikos kūrimas – tai geriausias būdas apsaugoti odą ir kartu sutaupyti milžiniškas sumas pinigų. Su „Natūralios kosmetikos vadovu“ išmoksite gaminti aukščiausios kokybės gaminius už nedidelę dalį to kainos, kurią mokėtumėte parduotuvėse. Taip išvengsite permokėjimo už komercinę, chemijos pilną kosmetiką, investuodami į prieinamas, švarias ir itin veiksmingas natūralias žaliavas.",
    text2: "Tai jūsų neįkainojamas vadovas pereinant prie sveikesnio gyvenimo būdo. Išskirtinių receptų dėka susigrąžinsite visišką kontrolę to, ką tepate ant savo kūno. Galite mėgautis rankų darbo gaminiais, kurie yra 100 % saugūs, ekologiški ir švelnūs tiek jūsų odai, tiek aplinkai.",
    cta: "PRADEDU GAMINTI!",
    imageAlt: "Sveika priežiūra",
  },

  finalCta: {
    urgencyLabel: "PASKUTINĖ DIENA UŽSISAKYTI",
    urgencySub: "už akcinę reklaminę kainą!",
    urgencyText:
      "Tai jūsų absoliučiai paskutinis šansas pasinaudoti mūsų išskirtiniu pasiūlymu ir prisijungti prie tūkstančių susižavėjusių studenčių!",
    offerPrice: "8.90 €",
    button: "GAUTI PRIEIGĄ DABAR!",
    productTitle: "Natūralios kosmetikos vadovas!",
    imageAlt: "Natūralios kosmetikos vadovas",
    bundleList: [
      "80 natūralios kosmetikos receptų",
      "Išsamus vadovas žingsnis po žingsnio",
      "Mokomasis žaliavų leksikonas",
      "Prieiga prie uždaros bendruomenės",
      "Ekspertų palaikymas visiems klausimams",
      "Patikrintas ir patikimas tiekėjų sąrašas",
    ],
    timerLabels: {
      days: "Dienos",
      hours: "Valandos",
      minutes: "Minutės",
      seconds: "Sekundės",
    },
  },

  footer: {
    tagline: "Atraskite su mumis, kaip sukurti tobulą natūralią kosmetiką!",
  },
};