// lib/copy.js
export const copy = {
  checkoutUrl: "https://www.oriopay.app/p/naturali-kosmetika",

  metadata: {
    title: "Natūralios kosmetikos vadovas | PerfuMaria das Ervas",
    description:
      "80 receptų 100 % natūraliai kosmetikai, kurią galite pasigaminti namuose. Išbandytos ir patikrintos formulės asmeniniam naudojimui arba verslo pradžiai.",
  },

  hero: {
    headlineLine1: "80 receptų",
    headlineHighlight: "NATŪRALIAI KOSMETIKAI",
    subheadline:
      "Gaukite prieigą prie slaptų 100 % natūralios kosmetikos receptų ir kurkite ją patogiai savo namuose! Išbandytos ir patikrintos formulės asmeniniam naudojimui arba nuosavo verslo pradžiai.",
    cta: "NORIU PRIEIGOS DABAR!",
    imageAlt: "Natūralios kosmetikos vadovas",
    timerLabels: {
      days: "Dienos",
      hours: "Valandos",
      minutes: "Minutės",
      seconds: "Sekundės",
    },
  },

  story: {
    text: "Dabar pateiksiu jums praktišką vadovą – tiesiai prie esmės, be jokių bereikalingų komplikacijų, bet itin patikimą, kad galėtumėte kurti savo 100 % natūralią kosmetiką namuose. Neišleisdami krūvos pinigų, nepriklausydami nuo tūkstančių ingredientų ir su galimybe naudoti ją sau, dovanoti artimiesiems ar net parduoti, jei norite susikurti naują pajamų šaltinį!",
    imageAlt: "Natūrali kosmetika",
  },

  recipeList: {
    headline: "Atraskite",
    headlineHighlight: "80 receptų,",
    headlineSuffix: "kuriuos gausite „Natūralios kosmetikos vadove“:",
    cta: "NORIU JŲ!",
    col1: [
      "Raminamasis kūno kremas",
      "Kūno kremas su pantenoliu",
      "Gaivinamasis kūno losjonas",
      "Kūno kremas-suflė",
      "Kūno sviestas su urukumu (anatu)",
      "Kietasis kūno sviestas",
      "Kūno aliejus",
      "Terapinis aliejus nuo dėmių ir strijų",
      "Dvifazis kūno aliejus",
      "Natūralus įdegio losjonas",
      "Skystas kūno muilas",
      "Dušo želė",
      "Kietasis kūno muilas su SCI",
      "Tradicinis kietasis kūno muilas",
      "Kreminis drėkinamasis muilas",
      "Šveičiamasis kūno muilas (Soap Body Scrub)",
      "Kūno šveitiklis",
      "Kūno šveitiklis su migdolų miltais",
      "Natūrali kūno priemonė su švytėjimo efektu",
      "Kūno purškiklis (Body Splash)",
      "Veido kremas su vitaminu C",
      "Veido kremas po saulės su levandomis",
      "Veido kremas su moliu",
      "Drėkinamasis veido losjonas su jazminais",
      "Sausasis veido aliejus (Dry Oil)",
      "Skystas veido muilas",
      "Veido prausimosi putos",
      "Veido serumas sausai ir jautriai odai",
      "Veido serumas riebiai odai",
      "Paakių serumas",
      "Veido tonikas sausai ir jautriai odai",
      "Gaivinamasis veido tonikas riebiai odai",
      "Veido valymo aliejus (Cleansing Oil)",
      "Veido valymo balzamas (Cleansing Balm)",
      "Muilas su raudonuoju moliu – Detoksikacija ir atgaivinimas",
      "Švelnus veido šveitiklis",
      "Veido gelis su salicilo rūgštimi",
      "Gelinė veido kaukė su hialurono rūgštimi",
      "Rožių veido eliksyras",
      "Veido purškiklis su alaviju",
      "Kaukė garbanotiems ir banguotiems plaukams",
    ],
    col2: [
      "Kaukė tiesiems ir šiek tiek banguotiems plaukams",
      "Kreminis kondicionierius",
      "Kietasis kondicionierius garbanotiems ir banguotiems plaukams",
      "Kietasis kondicionierius šiek tiek banguotiems ir tiesiems plaukams",
      "Kietasis šampūnas garbanotiems ir banguotiems plaukams",
      "Kietasis šampūnas tiesiems ir šiek tiek banguotiems plaukams",
      "Skystas šampūnas",
      "Kreminis šampūnas „2 viename“",
      "Vaikiškas šampūnas",
      "Nenuplaunamas kondicionierius (Leave-In)",
      "Nuo karščio apsaugantis plaukų purškiklis",
      "Plaukų aliejus",
      "Plaukų želė",
      "Natūrali plaukų pomada",
      "Drėkinamasis baigiamasis purškiklis",
      "Galvos odos šveitiklis",
      "Plaukų augimą skatinantis tonikas",
      "Serumas skilinėjantiems galiukams",
      "Plaukų kvepalai",
      "Natūralus intymios higienos muilas",
      "Natūralus vaikiškas kūno muilas",
      "Natūralūs skystieji kvepalai",
      "Natūralūs kietieji kvepalai",
      "Gelinė dantų pasta",
      "Burnos skalavimo skystis",
      "Purškiamasis dezodorantas",
      "Tepalas su medetkomis",
      "Tepalas su arnika",
      "Maitinamasis lūpų balzamas",
      "Natūralūs lūpų dažai",
      "Natūralus lūpų šveitiklis",
      "Purškiamasis makiažo valiklis",
      "Skutimosi putos",
      "Natūralus losjonas po skutimosi",
      "Rankų ir pėdų kremas",
      "Fiksuojamasis antakių gelis",
      "Natūrali masažinė žvakė",
      "Maitinamasis nagų ir odelių serumas",
      "Natūralus repelentas",
      "Atgaivinančios vonios druskos",
    ],
  },

  whatYouGet: {
    headline: "KĄ RASITE ŠIAME PUIKIAME VADOVE?",
    cta: "GAUTI VADOVĄ DABAR!",
    imageAlt: "Ką rasite vadove",
    items: [
      "Daugiau nei 80 išbandytų ir patikrintų receptų – įskaitant kreminį šveičiamąjį muilą, sausąjį veido aliejų, kūno purškiklį, apsaugą plaukams nuo karščio ir įvairias naujas formules.",
      "Kremų, gelių, šampūnų ir muilų bazės – išmokite kurti saugias ir personalizuotas formules kiekvienam odos bei plaukų tipui.",
      "Išsamus žingsnis po žingsnio vadovas pradedantiesiems ir pažengusiems – perpraskite viską nuo pagrindinių koncepcijų iki pačių sudėtingiausių technikų.",
      "Žaliavų katalogas – atraskite įvairių natūralių ingredientų naudą, kad sukurtumėte itin veiksmingą kosmetiką.",
      "Kosmetologijoje taikoma fitoterapija – kaip panaudoti gydomuosius augalus, siekiant sustiprinti kosmetikos poveikį.",
      "Natūralaus formulavimo paslaptys – pH reguliavimas, konservavimas, žaliavų parinkimas ir efektyvūs deriniai.",
      "Patarimai namų ir profesionaliai gamybai – įkurkite savo natūralios kosmetikos studiją ir tobulinkite technikas.",
      "Tvarumas ir rūpinimasis aplinka – išmokite kurti biologiškai skaidžią ir ekologišką kosmetiką.",
    ],
  },

  testimonials: {
    headline: "PAŽIŪRĖKITE, KĄ ŽMONĖS KALBA APIE NATŪRALIOS KOSMETIKOS VADOVĄ:",
    cta: "NORIU PRIEIGOS DABAR!",
    cards: [
      {
        name: "Marija S.",
        initials: "MS",
        color: "#16a34a",
        stars: 5,
        text: "Dievinu šį vadovą! Jau pasigaminau raminamąjį kūno kremą ir veido muilą, gavosi tiesiog nuostabiai. Daug geriau nei pramoniniai produktai, kuriuos naudojau anksčiau. Labai rekomenduoju!",
        source: "WhatsApp",
      },
      {
        name: "Elena G.",
        initials: "EG",
        color: "#0f766e",
        stars: 5,
        text: "Žmonės, koks nuostabus vadovas! Receptai labai detalūs ir lengvai suprantami. Jau pardaviau kelis produktus draugėms ir jos juos įsimylėjo. Vertingas kiekvienas centas!",
        source: "WhatsApp",
      },
      {
        name: "Silvija R.",
        initials: "SR",
        color: "#7c3aed",
        stars: 5,
        text: "Šiek tiek dvejojau prieš pirkdama, bet tikrai buvo verta! Žaliavų katalogas labai padėjo suprasti ingredientus. Jau išbandžiau 6 skirtingus receptus ir visi pavyko puikiai.",
        source: "WhatsApp",
      },
      {
        name: "Daiva M.",
        initials: "DM",
        color: "#b45309",
        stars: 5,
        text: "Kokia neįtikėtina investicija! Naudodamasi vadovu išmokau pasigaminti kietąjį šampūną ir kondicionierių. Mano plaukai dabar daug sveikesni, be to, kas mėnesį sutaupau nemažai pinigų. Ačiū jums!",
        source: "WhatsApp",
      },
    ],
  },

  autonomyIntro: {
    text1: "Su „Natūralios kosmetikos vadovu“ išmoksite kurti kosmetiką nuo pat pagrindų.",
    text2: "Jame žingsnis po žingsnio parodoma, kaip išsirinkti natūralius ingredientus, pritaikyti formules skirtingiems odos bei plaukų tipams ir personalizuoti produktus pagal savo poreikius.",
    text3: "Be to, įgausite pasitikėjimo ir savarankiškumo formuluojant, galėsite testuoti bei adaptuoti receptus, kad sukurtumėte unikalius produktus su savitu identitetu. Dėka detalaus natūralių žaliavų katalogo, pažinsite geriausius ingredientus ir išmoksite rasti tobulą derinį kiekvienam kosmetikos gaminiui.",
    cta: "GAUTI VADOVĄ DABAR!",
    imageAlt: "Nepriklausomybė natūralioje kosmetikoje",
  },

  benefitsList: {
    headline: "Nepriklausomybė ir kūrybiškumas natūralios kosmetikos srityje!",
    cta: "NORIU PRIEIGOS DABAR!",
    items: [
      {
        bold: "Išmokite kurti",
        rest: " kremus, serumus, šampūnus, muilus ir daug daugiau.",
      },
      {
        bold: "Atraskite, kaip išsirinkti",
        rest: " tinkamus ingredientus kiekvienam poreikiui.",
      },
      {
        bold: "Tapkite nepriklausomi nuo pramoninės kosmetikos ir",
        rest: " kurkite personalizuotas formules.",
      },
      {
        bold: "Pasinerkite į kosmetologijoje taikomą fitoterapiją,",
        rest: " išnaudodami gydomųjų augalų terapines savybes.",
      },
      {
        bold: "Sumažinkite išlaidas,",
        rest: " gamindami savo kosmetiką ir nedarydami jokių kompromisų kokybei.",
      },
      {
        bold: "Gaukite prieigą prie profesionalių formulių",
        rest: " ir išmokite saugiai kurti geriausius produktus.",
      },
      {
        bold: "Išsiskirkite natūralaus grožio rinkoje,",
        rest: " kuri vis labiau auga ir vertina tvarius gaminius.",
      },
      {
        bold: "Išmokite įkurti namų kosmetikos studiją",
        rest: " su praktiškais patarimais, kaip organizuoti darbo erdvę.",
      },
    ],
  },

  economy: {
    headline: "Sutaupymas ir verslo galimybės natūralių produktų rinkoje!",
    text1: "Nuosavos natūralios kosmetikos kūrimas – tai puiki galimybė tiek sutaupyti, tiek pradėti verslą. Su „Natūralios kosmetikos vadovu“ išmoksite gaminti aukštos kokybės kosmetiką už mažą kainą, išvengdami didelių išlaidų įprastiems produktams ir investuodami į prieinamus bei efektyvius natūralius ingredientus.",
    text2: "Jei norite pradėti savo verslą, tai neįkainojamas gidas, padėsiantis sukurti tvarų ir pelningą projektą. Naudodamiesi išskirtinėmis formulėmis ir praktiniais patarimais apie konservavimą, pakavimą bei rinkodarą, galite sukurti savo natūralios kosmetikos prekių ženklą, siūlydami rankų darbo produktus, atitinkančius sąmoningo ir ekologiško vartojimo tendencijas.",
    cta: "GAUTI VADOVĄ DABAR!",
    imageAlt: "Verslas natūralių produktų rinkoje",
  },

  finalCta: {
    urgencyLabel: "PASKUTINĖ DIENA UŽSISAKYTI",
    urgencySub: "už akcinę kainą!",
    urgencyText:
      "Tai jūsų paskutinis šansas pasinaudoti mūsų specialiu pasiūlymu ir tapti mūsų šeimos, turinčios tūkstančius patenkintų studenčių, dalimi!",
    offerPrice: "8.90 €",
    button: "GAUTI PRIEIGĄ DABAR!",
    productTitle: "Natūralios kosmetikos vadovas!",
    imageAlt: "Natūralios kosmetikos vadovas",
    bundleList: [
      "80 natūralios kosmetikos receptų",
      "Išsami mokomoji medžiaga",
      "Edukacinis žaliavų katalogas",
      "Studenčių bendruomenė",
      "Specializuotas palaikymas klausimams",
      "Tiekėjų sąrašas",
    ],
    timerLabels: {
      days: "Dienos",
      hours: "Valandos",
      minutes: "Minutės",
      seconds: "Sekundės",
    },
  },

  footer: {
    tagline: "Atraskite, kaip sukurti tobulą natūralią kosmetiką!",
    linkLabel: "Pilnas natūralios kosmetikos kursas",
    linkHref: "https://www.perfumariadaservas.shop",
  },
};